### PR TITLE
Support GHC 9.2

### PR DESCRIPTION
**Pull request by andreasabel**
Relax upper bounds (supporting GHC 9.2), include 9.2 in CI.

Successful CI run at: https://github.com/andreasabel/malcolm-wallace-universe/actions/runs/1409034526

Let me know if you want me to also implement these revisions on hackage.

UPDATE: 
- blocking https://github.com/haskell-infra/hackage-trustees/issues/320

### CODE REVIEW

**Comment by phadej** [comment]
HaXml is maintained at https://github.com/HaXml/HaXml

**Comment by andreasabel** [comment]
> HaXml is maintained at [HaXml/HaXml](https://github.com/HaXml/HaXml)

Ah, good to know!
I was mostly interested in `polyparse`, but then, CI runs for all four packages (including `HaXml`).

**Comment by phadej** [comment]
Let's see if CI passes. I think that in light of https://github.com/hackage-trustees/malcolm-wallace-universe/issues/9 iit wouldn't.

If it is so, it will be fine to comment out `HaXml` from `cabal.project`, it's a leaf package in this project.

**Comment by andreasabel** [comment]
CI passed.  OK if I make these revisions?:
- [ ] polyparse (base, bytestring) https://hackage.haskell.org/package/polyparse
- [ ] cpphs (time) https://hackage.haskell.org/package/cpphs

**Comment by phadej** [comment]
@andreasabel please do

**Pull request merged**
