### PR TITLE
HaXml-1.25.6

### PR DESCRIPTION
**Pull request by juhp**
bump 1.25.5 to 1.25.6 (#9)

### CODE REVIEW

**Comment by juhp** [comment]
Could someone approve the workflow?

**Comment by phadej** [comment]
As discussed, I don't like sharing `hackage-trustees` repositories for other then preparing NMUs. Please make your own fork.

**Comment by juhp** [comment]
I thought I was preparing a NMU...

**Comment by phadej** [comment]
@juhp: It's not an NMU, you are a maintainer now. https://hackage.haskell.org/package/HaXml/maintainers/

**Comment by juhp** [comment]
Yes I asked Malcolm this week... 👍

**Comment by juhp** [comment]
But I am pondering, would it be better to make a Malcolm Wallace universe org?

**Comment by phadej** [comment]
@juhp that's up to you (and malcolm).

**Pull request closed without merging**
