### PR TITLE
Make it compile with MicroHs

### PR DESCRIPTION
**Pull request by augustss**
Two changes:
The polyparse.cabal file is simply wrong
MicroHs does not have fail as a method in Monad

### CODE REVIEW

**Comment by phadej** [comment]
> The polyparse.cabal file is simply wrong

It's not. The standard has `fail` in `Monad`, and doens't have `MonadFail` in `base` library. So requiring `fail` for all other compilers than GHC is not wrong. It's required to write that way for e.g. Hugs (if `polyparse` worked with hugs, it actually might).

**Comment by augustss** [comment]
Fair enough.
But I don't know how to express the correct condition then. It would have to mention mhs, but hackage does not allow that. 
So you can leave it as is and it will still compile with hugs, but not with mhs.

**Comment by phadej** [comment]
I correct myself slightly. In a vacuum where the GHC is the only compiler, both are fine. In the universe where there are other compilers, neither is semantically right.

In this particular case we care about version of the *base*, as `Monad` is defined in `base` library. It's just happens that `base` and GHC versions are coupled. (And for the long time, `base` in Hugs is at constant version, if we want to consider some other compiler nevertheless).

So the correct approach is to encode "if base version >= 4.9" in `.cabal` file, which we can do using automatic flags

```
flag base49
  description: base >=4.9
  default: True
  manual: False
  
library
  hs-source-dirs:       src
  build-depends:        base >= 4.3.1.0 && < 5

  if flag(base49)
    build-depends: base >=4.9
  else
    build-depends: base <4.9
    build-depends: fail ==4.9.*

...
```

this is probably a good idea anyway, as there seem to be a push for reinstallable `base`, so decoupling GHC and base version conditions in `.cabal` files does make sense already on its own. Sadly, it's a bit verbose.

**Comment by augustss** [comment]
That seems like a good plan. MHS pretends to have a modern base.

**Comment by augustss** [comment]
I've made some more minor fixes and added CI for MicroHs.

**Comment by augustss** [comment]
Could you please merge or comment on the PR?

**Comment by gbaz** [comment]
looks good to me.

**Pull request merged**
